const seedArticles = [
  // Science & Tech
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Computer_science",
  "Internet",
  "Artificial_intelligence",
  "Space_exploration",
  "NASA",
  "Earth",
  "Sun",
  "Moon",
  "Solar_System",
  "Electricity",
  "Quantum_mechanics",
  "Evolution",
  "Genetics",
  "DNA",
  "Medicine",
  "Vaccination",
  "Climate_change",
  "Automobile",
  "Smartphone",
  "Robot",
  "Steam_engine",
  "Gravity",
  "Thermodynamics",
  "Telescope",
  "Microscope",
  "Lasers",

  // Geography & Countries
  "United_States",
  "United_Kingdom",
  "Canada",
  "Germany",
  "France",
  "Italy",
  "Japan",
  "China",
  "India",
  "Australia",
  "Brazil",
  "Russia",
  "Egypt",
  "South_Africa",
  "Mexico",
  "Spain",
  "Greece",
  "Sweden",
  "Switzerland",
  "Argentina",

  // Cities
  "London",
  "New_York_City",
  "Paris",
  "Tokyo",
  "Rome",
  "Washington,_D.C.",
  "Beijing",
  "Cairo",
  "Sydney",
  "Moscow",
  "Berlin",
  "Mumbai",
  "Toronto",
  "Los_Angeles",
  "Chicago",

  // Historical Events & Periods
  "World_War_I",
  "World_War_II",
  "Roman_Empire",
  "Ancient_Egypt",
  "Cold_War",
  "French_Revolution",
  "Industrial_Revolution",
  "Renaissance",
  "Middle_Ages",
  "American_Revolutionary_War",
  "Great_Depression",
  "Space_Race",
  "Russian_Revolution",
  "Viking_Age",
  "Black_Death",

  // Famous Figures (Science, History, Arts)
  "Albert_Einstein",
  "Isaac_Newton",
  "Marie_Curie",
  "Leonardo_da_Vinci",
  "William_Shakespeare",
  "Wolfgang_Amadeus_Mozart",
  "Mahatma_Gandhi",
  "Abraham_Lincoln",
  "Winston_Churchill",
  "Julius_Caesar",
  "Cleopatra",
  "Alexander_the_Great",
  "Christopher_Columbus",
  "Queen_Victoria",
  "Nelson_Mandela",
  "Martin_Luther_King_Jr.",
  "Charles_Darwin",
  "Galileo_Galilei",
  "Thomas_Edison",
  "Nikola_Tesla",
  "Stephen_Hawking",
  "Vincent_van_Gogh",
  "Ludwig_van_Beethoven",
  "Aristotle",
  "Plato",

  // Brands & Companies
  "Google",
  "Apple_Inc.",
  "Microsoft",
  "Amazon_(company)",
  "Meta_Platforms",
  "Tesla,_Inc.",
  "Netflix",
  "Coca-Cola",
  "McDonald%27s",
  "Disney",
  "Nintendo",
  "Sony",
  "SpaceX",
  "Toyota",
  "Samsung",

  // Animals & Nature
  "Dog",
  "Cat",
  "Horse",
  "Lion",
  "Tiger",
  "Elephant",
  "Whale",
  "Shark",
  "Bird",
  "Dinosaur",
  "Tree",
  "Flower",
  "Ocean",
  "Mountain",
  "Forest",
  "Desert",
  "River",
  "Volcano",
  "Rainforest",
  "Grand_Canyon",

  // General Culture & Daily Life
  "Language",
  "Music",
  "Art",
  "Literature",
  "Philosophy",
  "Religion",
  "Economics",
  "Law",
  "Education",
  "Food",
  "Coffee",
  "Tea",
  "Chocolate",
  "Beer",
  "Wine",
  "Agriculture",
  "Currency",
  "Photography",
  "Cinema",
  "Television",

  // Sports & Games
  "Olympic_Games",
  "FIFA_World_Cup",
  "Chess",
  "Football",
  "Basketball",
  "Tennis",
  "Cricket",
  "Baseball",
  "Golf",
  "Super_Bowl"
];

module.exports = seedArticles;
